---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-url-shortener
  template:
    metadata:
      labels:
        app: k8s-url-shortener
    spec:
      containers:
      - name: k8s-url-shortener
        image: belleysatish170/k8s-url-shortener:1
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-url-shortener-ingress
spec:
  rules:
  - host: <your-domain.com>  # Replace with your actual domain or leave empty for local testing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-url-shortener-service
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-url-shortener-service
spec:
  selector:
    app: k8s-url-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
